/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author DAM2
 */
public class RegisterView extends javax.swing.JFrame {

    /**
     * @return the inputConfirmarContra
     */
    public javax.swing.JPasswordField getInputConfirmarContra() {
        return inputConfirmarContra;
    }

    /**
     * @param inputConfirmarContra the inputConfirmarContra to set
     */
    public void setInputConfirmarContra(javax.swing.JPasswordField inputConfirmarContra) {
        this.inputConfirmarContra = inputConfirmarContra;
    }

    /**
     * @return the inputContra
     */
    public javax.swing.JTextField getInputContra() {
        return inputContra;
    }

    /**
     * @param inputContra the inputContra to set
     */
    public void setInputContra(javax.swing.JPasswordField inputContra) {
        this.inputContra = inputContra;
    }

    public javax.swing.JButton getBotonRegistro() {
        return botonRegistro;
    }

    /**
     * @param botonRegistro the botonRegistro to set
     */
    public void setBotonRegistro(javax.swing.JButton botonRegistro) {
        this.botonRegistro = botonRegistro;
    }

    /**
     * @return the inputContra
     */
    /**
     * @param inputContra the inputContra to set
     */
    /**
     * @return the inputUser
     */
    public javax.swing.JTextField getInputUser() {
        return inputUser;
    }

    /**
     * @param inputUser the inputUser to set
     */
    public void setInputUser(javax.swing.JTextField inputUser) {
        this.inputUser = inputUser;
    }

    /**
     * @return the labelContra
     */
    public javax.swing.JLabel getLabelContra() {
        return labelContra;
    }

    /**
     * @param labelContra the labelContra to set
     */
    public void setLabelContra(javax.swing.JLabel labelContra) {
        this.labelContra = labelContra;
    }

    /**
     * @return the labelCredenciales
     */
    public javax.swing.JLabel getLabelCredenciales() {
        return labelCredenciales;
    }

    /**
     * @param labelCredenciales the labelCredenciales to set
     */
    public void setLabelCredenciales(javax.swing.JLabel labelCredenciales) {
        this.labelCredenciales = labelCredenciales;
    }

    /**
     * @return the labelUser
     */
    public javax.swing.JLabel getLabelUser() {
        return labelUser;
    }

    /**
     * @param labelUser the labelUser to set
     */
    public void setLabelUser(javax.swing.JLabel labelUser) {
        this.labelUser = labelUser;
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RegisterView.class.getName());

    /**
     * Creates new form LoginView
     */
    public RegisterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCredenciales = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        labelContra = new javax.swing.JLabel();
        inputUser = new javax.swing.JTextField();
        botonRegistro = new javax.swing.JButton();
        inputContra = new javax.swing.JPasswordField();
        inputConfirmarContra = new javax.swing.JPasswordField();
        labelContra1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelCredenciales.setPreferredSize(new java.awt.Dimension(100, 25));

        labelUser.setText("Usuario");

        labelContra.setText("Contraseña");

        botonRegistro.setText("Registro");

        labelContra1.setText("Contraseña");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(botonRegistro)
                .addGap(176, 176, 176))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelContra, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(labelUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelContra1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputUser)
                            .addComponent(inputContra, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(inputConfirmarContra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(labelCredenciales, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUser)
                    .addComponent(inputUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContra1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputConfirmarContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(botonRegistro)
                .addGap(31, 31, 31)
                .addComponent(labelCredenciales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RegisterView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRegistro;
    private javax.swing.JPasswordField inputConfirmarContra;
    private javax.swing.JPasswordField inputContra;
    private javax.swing.JTextField inputUser;
    private javax.swing.JLabel labelContra;
    private javax.swing.JLabel labelContra1;
    private javax.swing.JLabel labelCredenciales;
    private javax.swing.JLabel labelUser;
    // End of variables declaration//GEN-END:variables
}
